name: Container Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Local Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: secure-app:latest

      - name: Run Trivy Container Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'secure-app:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
