name: IaC Security

on:
  workflow_call:
  push:
    branches: [ main ]

jobs:
  iac-security:
    name: Scan Infrastructure as Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkov IaC Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: iac/
          framework: dockerfile,terraform,kubernetes
          output_format: cli
