name: SAST and Secret Scanning

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  sast:
    name: Code and Secret Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Semgrep SARIF Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }} # Optional, leave if unneeded
        continue-on-error: true

      - name: Run Semgrep CLI Scan to SARIF
        run: |
          pip install semgrep
          semgrep scan --sarif --output semgrep.sarif
        continue-on-error: true

      - name: Upload Semgrep SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'semgrep.sarif'
